server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: order_route
          uri: http://localhost:8091
          predicates:
            - Path=/orders/**
        - id: inventory_route
          uri: http://localhost:8092
          predicates:
            - Path=/inventory/**
