server:
  port: 8091

spring:
  application:
    name: order-service
    kafka:
      bootstrap-servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer


eureka:
  client:
    service-url:
      defaultZone: http://order-service:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 4
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
  retry:
    instances:
      inventoryService:
        maxAttempts: 2
        waitDuration: 500ms
  timelimiter:
    instances:
      inventoryService:
        timeoutDuration: 2s
  bulkhead:
    instances:
      inventoryService:
        maxConcurrentCalls: 5
