version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - postgres

  inventory-service:
    build: ./inventory-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - postgres

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - inventory-service
      - postgres

  api-gateway:
    build: ./api-gateway
    ports:
      - "9000:9000"
    depends_on:
      - eureka-server
      - order-service
      - inventory-service

volumes:
  pgdata:
