server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
resilience4j:
  circuitbreaker:
    instances:
      demoCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
#        automaticTransitionFromOpenToHalfOpenEnabled:true
  retry:
    instances:
      globalRetry:
        maxAttempts: 3
        waitDuration: 300ms
  ratelimiter:
    instances:
      demoRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms
  timelimiter:
    instances:
      demoTimeLimiter:
        timeoutDuration: 1s #otar theke eta besi
  bulkhead:
    thread-pool:
      demoBulkhead:
        coreThreadPoolSize: 3
        maxThreadPoolSize: 4
        queueCapacity: 4
        maxWaitDuration: 2s
  metrics:
    binders:
          - retry
          - circuitbreaker
          - ratelimiter
          - timelimiter
          - bulkhead
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true